# Header
menu:
  home: /
  about: /about

# Title on top left of menu. Leave empty to use main blog title
menu_title:

# URL of the Home page image
index_cover: /images/hero01.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-23373956-1

# Addthis ID
addthis:

# Social Accounts
twitter_url: 
twitter_handle: 
facebook_url:
github_url: https://github.com/h0ke
rss_feed: https://h0ke.com/atom.xml
fhpx_url: https://500px.com/h0ke
gitlab_url:
linkedin_url: https://www.linkedin.com/in/matthewhokanson
mailto: m@h0ke.com